// Config plugin for the local step-counting native module.
//
// `android/` is gitignored and regenerated by `expo prebuild`, so anything
// hand-edited in there survives exactly until the next prebuild — which is how
// this module nearly got lost in the SDK 56 upgrade. The Kotlin sources now
// live in `native/android/steps/` (tracked), and this plugin re-applies them
// plus their manifest wiring on every prebuild.
//
// What it restores:
//   - the Kotlin package (foreground service, ring buffer, store, RN bridge)
//   - `add(StepServicePackage())` in MainApplication's package list
//   - the foreground service declaration, health permissions, and the Health
//     Connect rationale intent-filter/alias that androidx.health requires
const fs = require('fs');
const path = require('path');
const {
  withAndroidManifest,
  withMainApplication,
  withDangerousMod,
  AndroidConfig,
} = require('@expo/config-plugins');

const SUBPACKAGE = 'steps';
const SOURCE_DIR = path.join('native', 'android', 'steps');

const PERMISSIONS = [
  'android.permission.ACTIVITY_RECOGNITION',
  'android.permission.FOREGROUND_SERVICE',
  'android.permission.FOREGROUND_SERVICE_HEALTH',
  'android.permission.POST_NOTIFICATIONS',
  'android.permission.health.READ_STEPS',
];

const SERVICE_NAME = `.${SUBPACKAGE}.StepCounterService`;
const ALIAS_NAME = 'ViewPermissionUsageActivity';

function withStepKotlinSources(config) {
  return withDangerousMod(config, [
    'android',
    async (cfg) => {
      const androidPackage = cfg.android && cfg.android.package;
      if (!androidPackage) {
        throw new Error('withStepService: expo.android.package must be set in the app config.');
      }

      const src = path.join(cfg.modRequest.projectRoot, SOURCE_DIR);
      if (!fs.existsSync(src)) {
        throw new Error(`withStepService: missing Kotlin sources at ${SOURCE_DIR}`);
      }

      const dest = path.join(
        cfg.modRequest.platformProjectRoot,
        'app', 'src', 'main', 'java',
        ...androidPackage.split('.'),
        SUBPACKAGE
      );
      fs.mkdirSync(dest, { recursive: true });

      for (const file of fs.readdirSync(src)) {
        if (file.endsWith('.kt')) {
          fs.copyFileSync(path.join(src, file), path.join(dest, file));
        }
      }
      return cfg;
    },
  ]);
}

function withStepPackageRegistered(config) {
  return withMainApplication(config, (cfg) => {
    const androidPackage = cfg.android.package;
    const importLine = `import ${androidPackage}.${SUBPACKAGE}.StepServicePackage`;
    let contents = cfg.modResults.contents;

    if (!contents.includes(importLine)) {
      contents = contents.replace(/^(package .*)$/m, `$1\n\n${importLine}`);
    }

    if (!contents.includes('add(StepServicePackage())')) {
      const addition = '\n          // Local module: foreground step-counting service.\n          add(StepServicePackage())';
      // Template moved between RN versions: 0.74 returned the list from
      // `getPackages()` inside a ReactNativeHost, 0.85 passes it to
      // ExpoReactHostFactory as `packageList = PackageList(this).packages.apply {}`.
      // Match the list expression itself rather than what surrounds it.
      if (/PackageList\(this\)\.packages\.apply\s*\{/.test(contents)) {
        contents = contents.replace(
          /(PackageList\(this\)\.packages\.apply\s*\{)/,
          `$1${addition}`
        );
      } else {
        contents = contents.replace(
          /PackageList\(this\)\.packages(?!\.)/,
          `PackageList(this).packages.apply {${addition}\n        }`
        );
      }
    }

    cfg.modResults.contents = contents;
    return cfg;
  });
}

function withStepManifest(config) {
  const withPerms = AndroidConfig.Permissions.withPermissions(config, PERMISSIONS);

  return withAndroidManifest(withPerms, (cfg) => {
    const manifest = cfg.modResults;
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(manifest);
    const activity = AndroidConfig.Manifest.getMainActivityOrThrow(manifest);

    application.service = application.service || [];
    if (!application.service.some((s) => s.$ && s.$['android:name'] === SERVICE_NAME)) {
      application.service.push({
        $: {
          'android:name': SERVICE_NAME,
          'android:enabled': 'true',
          'android:exported': 'false',
          'android:foregroundServiceType': 'health',
        },
      });
    }

    // Health Connect will not grant read access unless the app can show a
    // rationale screen, which it finds through this filter and the alias below.
    activity['intent-filter'] = activity['intent-filter'] || [];
    const hasRationale = activity['intent-filter'].some(
      (f) => f.action && f.action.some((a) => a.$['android:name'] === 'android.intent.action.VIEW_PERMISSION_USAGE')
    );
    if (!hasRationale) {
      activity['intent-filter'].push({
        action: [{ $: { 'android:name': 'android.intent.action.VIEW_PERMISSION_USAGE' } }],
        category: [{ $: { 'android:name': 'android.intent.category.HEALTH_PERMISSIONS' } }],
      });
    }

    application['activity-alias'] = application['activity-alias'] || [];
    if (!application['activity-alias'].some((a) => a.$ && a.$['android:name'] === ALIAS_NAME)) {
      application['activity-alias'].push({
        $: {
          'android:name': ALIAS_NAME,
          'android:targetActivity': '.MainActivity',
          'android:exported': 'true',
          'android:permission': 'android.permission.START_VIEW_PERMISSION_USAGE',
        },
        'intent-filter': [
          { action: [{ $: { 'android:name': 'androidx.health.ACTION_SHOW_PERMISSIONS_RATIONALE' } }] },
        ],
      });
    }

    return cfg;
  });
}

module.exports = function withStepService(config) {
  return withStepManifest(withStepPackageRegistered(withStepKotlinSources(config)));
};
